### ISSUE TITLE
MOTD and WHOIS info are not visible on mobile

### ISSUE THREAD

**Issue by brettgilio** [dracula/thelounge#3]
MOTD and WHOIS info is not visible in this theme

![Screenshot_20210919-203258_Chrome](https://user-images.githubusercontent.com/22002698/133950048-06bb0be9-0ea8-4c97-9b58-b24a86a793f4.jpg)
![Screenshot_20210919-203320_Chrome](https://user-images.githubusercontent.com/22002698/133950050-44c48cd6-e92f-48cf-9354-248b960bb224.jpg)

**Comment by ronilaukkarinen** [comment]
It seems this is due to the default table-like list data structure. In default theme it's also like this but without the main cell that aligns the items.

One option is to remove all margins on mobile. We could perhaps remove the "icon column" as well to save space:

![Screen-Shot-2021-09-20-08-40-46 73](https://user-images.githubusercontent.com/1534150/133960971-64bbc72e-d95e-4bdc-ad65-5a99a4b2ee5b.png)

Should be rather easy to fix but I'm too busy right now and my main focus is currently on [midnight theme](https://github.com/ronilaukkarinen/thelounge-theme-midnight) so right now this is not a top priority for me. Pull requests welcome.

**Comment by ronilaukkarinen** [comment]
I have renamed the issuea accordingly. Please open separate issues on other things, this issue will be about the whois style bug.

**Comment by ronilaukkarinen** [comment]
Fixed in 1.0.4. Thanks @benyafai!
